#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-bacon
Version  : 1.2.0
Release  : 8
URL      : https://rubygems.org/downloads/bacon-1.2.0.gem
Source0  : https://rubygems.org/downloads/bacon-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-bacon-bin
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= Bacon -- small RSpec clone.
"Truth will sooner come out from error than from confusion."
---Francis Bacon

%package bin
Summary: bin components for the rubygem-bacon package.
Group: Binaries

%description bin
bin components for the rubygem-bacon package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n bacon-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-bacon.gemspec

%build
gem build rubygem-bacon.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
bacon-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
pushd %{buildroot}%{gem_dir}/gems/bacon-1.2.0
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/bacon-1.2.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Autotest/Bacon/cdesc-Bacon.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Autotest/Bacon/make_test_cmd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Autotest/Bacon/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Autotest/BaconRspec/cdesc-BaconRspec.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Autotest/cdesc-Autotest.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/SpecDoxOutput/cdesc-SpecDoxOutput.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/SpecDoxOutput/handle_requirement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/SpecDoxOutput/handle_specification-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/SpecDoxOutput/handle_summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/SpecDoxOutput/spaces-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/FalseClass/cdesc-FalseClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/FalseClass/false%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Kernel/describe-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Kernel/shared-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/after-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/before-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/behaves_like-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/cdesc-Context.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/change%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/context;/cdesc-context;.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/describe-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/it-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/raise%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/run_requirement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/should-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Context/throw%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Error/count_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/Error/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/cdesc-KnockOutput.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/handle_requirement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/handle_specification-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/KnockOutput/handle_summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Numeric/cdesc-Numeric.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Numeric/close%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Object/false%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Object/should-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Object/true%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Proc/cdesc-Proc.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Proc/change%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Proc/raise%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Proc/throw%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/an-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/be-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/cdesc-Should.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/flunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/identical_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/not-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/same_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/Should/satisfy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/TrueClass/cdesc-TrueClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/TrueClass/true%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/cdesc-TapOutput.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/handle_requirement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/handle_specification-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/TapOutput/handle_summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/cdesc-TestUnitOutput.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/handle_requirement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/handle_specification-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/TestUnitOutput/handle_summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/cdesc-Bacon.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/summary_at_exit-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/Bacon/summary_on_exit-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/page-RDOX.ri
/usr/lib64/ruby/gems/2.2.0/doc/bacon-1.2.0/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/COPYING
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/ChangeLog
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/RDOX
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/bacon.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/bin/bacon
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/lib/autotest/bacon.rb
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/lib/autotest/bacon_rspec.rb
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/lib/autotest/discover.rb
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/lib/bacon.rb
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/test/spec_bacon.rb
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/test/spec_nontrue.rb
/usr/lib64/ruby/gems/2.2.0/gems/bacon-1.2.0/test/spec_should.rb
/usr/lib64/ruby/gems/2.2.0/specifications/bacon-1.2.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/bacon
