#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-bacon
Version  : 1.2.0
Release  : 10
URL      : https://rubygems.org/downloads/bacon-1.2.0.gem
Source0  : https://rubygems.org/downloads/bacon-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-bacon-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
= Bacon -- small RSpec clone.
"Truth will sooner come out from error than from confusion."
---Francis Bacon

%package bin
Summary: bin components for the rubygem-bacon package.
Group: Binaries

%description bin
bin components for the rubygem-bacon package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n bacon-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-bacon.gemspec

%build
gem build rubygem-bacon.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
bacon-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/bacon-1.2.0
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/bacon-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/ChangeLog
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/RDOX
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/bacon.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/bin/bacon
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/lib/autotest/bacon.rb
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/lib/autotest/bacon_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/lib/autotest/discover.rb
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/lib/bacon.rb
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/test/spec_bacon.rb
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/test/spec_nontrue.rb
/usr/lib64/ruby/gems/2.3.0/gems/bacon-1.2.0/test/spec_should.rb
/usr/lib64/ruby/gems/2.3.0/specifications/bacon-1.2.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/bacon
